[package]
name = "rbar"
version = "0.1.0"
edition = "2024"

[dependencies]
gio = "0.21.1"
gtk4 = { version = "0.10.0", features = ["v4_12"] }
gtk4-layer-shell = "0.6.3"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
